# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleDriveDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
    pod 'Google/SignIn', '~> 3.0.3'
  # Pods for GoogleDriveDemo

end
